# Generated by Django 3.2.7 on 2021-09-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tage',
        ),
        migrations.AlterField(
            model_name='review',
            name='vote',
            field=models.CharField(choices=[('up', 'Up vote'), ('down', 'Down Vote')], default='up', max_length=200),
        ),
    ]
